/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-10-05 ( Date ISO 2024-10-05 - Time 14:42:55 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package sn.afrik.tech.solidarite_360.services.evt;
import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;

import sn.afrik.tech.solidarite_360.entities.evt.Activite;

/**
 * Service Interface for managing {@link Activite}.
*  @author aek
 */
public interface IActiviteService  {
   
    /**
     * create new item for domain
     *
     * @param entity entity to save.
     * @return persisted entity Activite
     */
    Activite create(Activite d);

    /**
     * Update entity. Check before if existing data. If data is empty throw Exception
     *
     * @param entity domain
     * @param id of entity
     * @return Activite
     */
    Activite update(Activite d);

    /**
     * get Activite by id. Can be return empty
     *
     * @param id the id of the entity.
     * @return Activite
     */
    Activite getOne(Long id) ;

    /**
     * Get all entities
     *
     * @return list of entities List<Activite>
     */
    List<Activite> getAll();

    /**
     * Count item in entity
     *
     * @return long 
     */
    long getTotal();

    /**
     * Delete record by id
     *  
     */
    void delete(Long id);

    /**
     * Find all with pagination
     *
     * @return Page<Activite>  
     */
    Page<Activite> findAllPaginate(Pageable pageable);

    /**
     * Find all with pagination  by criteria 
     *
     * @return Page<Activite>  
     */
	Page<Activite> findAllSpecification(Specification<Activite> specs, Pageable pageable);

}
