/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-10-05 ( Date ISO 2024-10-05 - Time 14:43:01 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package sn.afrik.tech.solidarite_360.services.evt;
import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;

import sn.afrik.tech.solidarite_360.entities.evt.Reunion;

/**
 * Service Interface for managing {@link Reunion}.
*  @author aek
 */
public interface IReunionService  {
   
    /**
     * create new item for domain
     *
     * @param entity entity to save.
     * @return persisted entity Reunion
     */
    Reunion create(Reunion d);

    /**
     * Update entity. Check before if existing data. If data is empty throw Exception
     *
     * @param entity domain
     * @param id of entity
     * @return Reunion
     */
    Reunion update(Reunion d);

    /**
     * get Reunion by id. Can be return empty
     *
     * @param id the id of the entity.
     * @return Reunion
     */
    Reunion getOne(Long id) ;

    /**
     * Get all entities
     *
     * @return list of entities List<Reunion>
     */
    List<Reunion> getAll();

    /**
     * Count item in entity
     *
     * @return long 
     */
    long getTotal();

    /**
     * Delete record by id
     *  
     */
    void delete(Long id);

    /**
     * Find all with pagination
     *
     * @return Page<Reunion>  
     */
    Page<Reunion> findAllPaginate(Pageable pageable);

    /**
     * Find all with pagination  by criteria 
     *
     * @return Page<Reunion>  
     */
	Page<Reunion> findAllSpecification(Specification<Reunion> specs, Pageable pageable);

}
