/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-10-05 ( Date ISO 2024-10-05 - Time 15:16:59 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package sn.afrik.tech.solidarite_360.controllers;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import jakarta.validation.Valid;
import sn.afrik.tech.solidarite_360.entities.Feedback;
import sn.afrik.tech.solidarite_360.services.impl.FeedbackService;


/**
 * REST controller for managing {@link Feedback}.
 *
 * @author @aek
 */
@RestController
@RequestMapping("/api/feedback")
public class FeedbackCtrl {

    private final Logger log = LoggerFactory.getLogger(FeedbackCtrl.class);
	
    private final FeedbackService entityService;

 	public FeedbackCtrl (FeedbackService entityService) {
		this.entityService = entityService;
	}

    /**
     * {@code POST  /feedback} : Create a new feedback.
     *
     * @param feedback the feedback to create.
     * @return the {@link ResponseEntity} with status {@code 201 (Created)} and with body the new feedback.
     */
	@PostMapping()
	public ResponseEntity<Feedback> createFeedback(@RequestBody @Valid Feedback feedback) {
         log.debug("REST request to save Feedback : {}", feedback);
         return new ResponseEntity<>(entityService.create(feedback), HttpStatus.CREATED);
    }

   /**
     * {@code PUT  /feedback} : Updates an existing feedback.
     *
     * @param feedback the feedback to update.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the updated feedback,
     * or with status {@code 400 (Bad Request)} if the feedback is not valid,
     * or with status {@code 500 (Internal Server Error)} if the feedback couldn't be updated.
     */
    @PutMapping()
    public ResponseEntity<Feedback> updateFeedback(@Valid @RequestBody Feedback feedback) {
        log.debug("REST request to update Feedback : {}", feedback);
        Feedback result = entityService.update(feedback);
        return ResponseEntity.ok().body(result);
    }

    /**
     * {@code GET  /feedback} : get all the feedbacks.
     *
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the list of feedback in body.
     */

    @GetMapping()
    public ResponseEntity<List<Feedback>> getAllFeedback() {
	    log.debug("REST request to get all feedbacks");
        List<Feedback> lst = entityService.getAll();

        return new ResponseEntity<>(lst,HttpStatus.OK);
    }

    /**
     * {@code GET  /feedback/:id} : get the "id" feedback.
     *
     * @param id the id of the feedback to retrieve.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the feedback, or with status {@code 404 (Not Found)}.
     */
    @GetMapping(value = "/{id}")
    public ResponseEntity<Feedback> getOneFeedback(@PathVariable("id") Long id) {
        log.debug("REST request to get Feedback : {}", id);
        Feedback e = entityService.getOne(id);

        return new ResponseEntity<>(e, HttpStatus.OK);
    }

  /**
     * {@code DELETE  /feedback/:id} : delete the "id" feedback.
     *
     * @param id the id of the feedback to delete.
     * @return the {@link ResponseEntity} with status {@code 204 (NO_CONTENT)}.
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteFeedback(@PathVariable("id") Long id) {
        log.debug("REST request to delete Feedback : {}", id);
        entityService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

}
