/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-10-05 ( Date ISO 2024-10-05 - Time 15:16:59 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package sn.afrik.tech.solidarite_360.controllers;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import jakarta.validation.Valid;
import sn.afrik.tech.solidarite_360.entities.Recompense;
import sn.afrik.tech.solidarite_360.services.impl.RecompenseService;


/**
 * REST controller for managing {@link Recompense}.
 *
 * @author @aek
 */
@RestController
@RequestMapping("/api/recompense")
public class RecompenseCtrl {

    private final Logger log = LoggerFactory.getLogger(RecompenseCtrl.class);
	
    private final RecompenseService entityService;

 	public RecompenseCtrl (RecompenseService entityService) {
		this.entityService = entityService;
	}

    /**
     * {@code POST  /recompense} : Create a new recompense.
     *
     * @param recompense the recompense to create.
     * @return the {@link ResponseEntity} with status {@code 201 (Created)} and with body the new recompense.
     */
	@PostMapping()
	public ResponseEntity<Recompense> createRecompense(@RequestBody @Valid Recompense recompense) {
         log.debug("REST request to save Recompense : {}", recompense);
         return new ResponseEntity<>(entityService.create(recompense), HttpStatus.CREATED);
    }

   /**
     * {@code PUT  /recompense} : Updates an existing recompense.
     *
     * @param recompense the recompense to update.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the updated recompense,
     * or with status {@code 400 (Bad Request)} if the recompense is not valid,
     * or with status {@code 500 (Internal Server Error)} if the recompense couldn't be updated.
     */
    @PutMapping()
    public ResponseEntity<Recompense> updateRecompense(@Valid @RequestBody Recompense recompense) {
        log.debug("REST request to update Recompense : {}", recompense);
        Recompense result = entityService.update(recompense);
        return ResponseEntity.ok().body(result);
    }

    /**
     * {@code GET  /recompense} : get all the recompenses.
     *
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the list of recompense in body.
     */

    @GetMapping()
    public ResponseEntity<List<Recompense>> getAllRecompense() {
	    log.debug("REST request to get all recompenses");
        List<Recompense> lst = entityService.getAll();

        return new ResponseEntity<>(lst,HttpStatus.OK);
    }

    /**
     * {@code GET  /recompense/:id} : get the "id" recompense.
     *
     * @param id the id of the recompense to retrieve.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the recompense, or with status {@code 404 (Not Found)}.
     */
    @GetMapping(value = "/{id}")
    public ResponseEntity<Recompense> getOneRecompense(@PathVariable("id") Long id) {
        log.debug("REST request to get Recompense : {}", id);
        Recompense e = entityService.getOne(id);

        return new ResponseEntity<>(e, HttpStatus.OK);
    }

  /**
     * {@code DELETE  /recompense/:id} : delete the "id" recompense.
     *
     * @param id the id of the recompense to delete.
     * @return the {@link ResponseEntity} with status {@code 204 (NO_CONTENT)}.
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteRecompense(@PathVariable("id") Long id) {
        log.debug("REST request to delete Recompense : {}", id);
        entityService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

}
