/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-10-05 ( Date ISO 2024-10-05 - Time 14:42:59 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package sn.afrik.tech.solidarite_360.services.doc;
import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;

import sn.afrik.tech.solidarite_360.entities.doc.CompteRendu;

/**
 * Service Interface for managing {@link CompteRendu}.
*  @author aek
 */
public interface ICompteRenduService  {
   
    /**
     * create new item for domain
     *
     * @param entity entity to save.
     * @return persisted entity CompteRendu
     */
    CompteRendu create(CompteRendu d);

    /**
     * Update entity. Check before if existing data. If data is empty throw Exception
     *
     * @param entity domain
     * @param id of entity
     * @return CompteRendu
     */
    CompteRendu update(CompteRendu d);

    /**
     * get CompteRendu by id. Can be return empty
     *
     * @param id the id of the entity.
     * @return CompteRendu
     */
    CompteRendu getOne(Long id) ;

    /**
     * Get all entities
     *
     * @return list of entities List<CompteRendu>
     */
    List<CompteRendu> getAll();

    /**
     * Count item in entity
     *
     * @return long 
     */
    long getTotal();

    /**
     * Delete record by id
     *  
     */
    void delete(Long id);

    /**
     * Find all with pagination
     *
     * @return Page<CompteRendu>  
     */
    Page<CompteRendu> findAllPaginate(Pageable pageable);

    /**
     * Find all with pagination  by criteria 
     *
     * @return Page<CompteRendu>  
     */
	Page<CompteRendu> findAllSpecification(Specification<CompteRendu> specs, Pageable pageable);

}
