/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-10-05 ( Date ISO 2024-10-05 - Time 14:42:59 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package sn.afrik.tech.solidarite_360.services.doc;
import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;

import sn.afrik.tech.solidarite_360.entities.doc.Document;

/**
 * Service Interface for managing {@link Document}.
*  @author aek
 */
public interface IDocumentService  {
   
    /**
     * create new item for domain
     *
     * @param entity entity to save.
     * @return persisted entity Document
     */
    Document create(Document d);

    /**
     * Update entity. Check before if existing data. If data is empty throw Exception
     *
     * @param entity domain
     * @param id of entity
     * @return Document
     */
    Document update(Document d);

    /**
     * get Document by id. Can be return empty
     *
     * @param id the id of the entity.
     * @return Document
     */
    Document getOne(Long id) ;

    /**
     * Get all entities
     *
     * @return list of entities List<Document>
     */
    List<Document> getAll();

    /**
     * Count item in entity
     *
     * @return long 
     */
    long getTotal();

    /**
     * Delete record by id
     *  
     */
    void delete(Long id);

    /**
     * Find all with pagination
     *
     * @return Page<Document>  
     */
    Page<Document> findAllPaginate(Pageable pageable);

    /**
     * Find all with pagination  by criteria 
     *
     * @return Page<Document>  
     */
	Page<Document> findAllSpecification(Specification<Document> specs, Pageable pageable);

}
