/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-10-05 ( Date ISO 2024-10-05 - Time 14:43:01 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package sn.afrik.tech.solidarite_360.services.doc;
import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;

import sn.afrik.tech.solidarite_360.entities.doc.Media;

/**
 * Service Interface for managing {@link Media}.
*  @author aek
 */
public interface IMediaService  {
   
    /**
     * create new item for domain
     *
     * @param entity entity to save.
     * @return persisted entity Media
     */
    Media create(Media d);

    /**
     * Update entity. Check before if existing data. If data is empty throw Exception
     *
     * @param entity domain
     * @param id of entity
     * @return Media
     */
    Media update(Media d);

    /**
     * get Media by id. Can be return empty
     *
     * @param id the id of the entity.
     * @return Media
     */
    Media getOne(Long id) ;

    /**
     * Get all entities
     *
     * @return list of entities List<Media>
     */
    List<Media> getAll();

    /**
     * Count item in entity
     *
     * @return long 
     */
    long getTotal();

    /**
     * Delete record by id
     *  
     */
    void delete(Long id);

    /**
     * Find all with pagination
     *
     * @return Page<Media>  
     */
    Page<Media> findAllPaginate(Pageable pageable);

    /**
     * Find all with pagination  by criteria 
     *
     * @return Page<Media>  
     */
	Page<Media> findAllSpecification(Specification<Media> specs, Pageable pageable);

}
