/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-10-05 ( Date ISO 2024-10-05 - Time 15:16:59 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package sn.afrik.tech.solidarite_360.controllers.evt;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import jakarta.validation.Valid;
import sn.afrik.tech.solidarite_360.entities.evt.PresenceReunion;
import sn.afrik.tech.solidarite_360.services.impl.PresenceReunionService;


/**
 * REST controller for managing {@link PresenceReunion}.
 *
 * @author @aek
 */
@RestController
@RequestMapping("/api/presenceReunion")
public class PresenceReunionCtrl {

    private final Logger log = LoggerFactory.getLogger(PresenceReunionCtrl.class);
	
    private final PresenceReunionService entityService;

 	public PresenceReunionCtrl (PresenceReunionService entityService) {
		this.entityService = entityService;
	}

    /**
     * {@code POST  /presenceReunion} : Create a new presenceReunion.
     *
     * @param presenceReunion the presenceReunion to create.
     * @return the {@link ResponseEntity} with status {@code 201 (Created)} and with body the new presenceReunion.
     */
	@PostMapping()
	public ResponseEntity<PresenceReunion> createPresenceReunion(@RequestBody @Valid PresenceReunion presenceReunion) {
         log.debug("REST request to save PresenceReunion : {}", presenceReunion);
         return new ResponseEntity<>(entityService.create(presenceReunion), HttpStatus.CREATED);
    }

   /**
     * {@code PUT  /presenceReunion} : Updates an existing presenceReunion.
     *
     * @param presenceReunion the presenceReunion to update.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the updated presenceReunion,
     * or with status {@code 400 (Bad Request)} if the presenceReunion is not valid,
     * or with status {@code 500 (Internal Server Error)} if the presenceReunion couldn't be updated.
     */
    @PutMapping()
    public ResponseEntity<PresenceReunion> updatePresenceReunion(@Valid @RequestBody PresenceReunion presenceReunion) {
        log.debug("REST request to update PresenceReunion : {}", presenceReunion);
        PresenceReunion result = entityService.update(presenceReunion);
        return ResponseEntity.ok().body(result);
    }

    /**
     * {@code GET  /presenceReunion} : get all the presenceReunions.
     *
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the list of presenceReunion in body.
     */

    @GetMapping()
    public ResponseEntity<List<PresenceReunion>> getAllPresenceReunion() {
	    log.debug("REST request to get all presenceReunions");
        List<PresenceReunion> lst = entityService.getAll();

        return new ResponseEntity<>(lst,HttpStatus.OK);
    }

    /**
     * {@code GET  /presenceReunion/:id} : get the "id" presenceReunion.
     *
     * @param id the id of the presenceReunion to retrieve.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the presenceReunion, or with status {@code 404 (Not Found)}.
     */
    @GetMapping(value = "/{id}")
    public ResponseEntity<PresenceReunion> getOnePresenceReunion(@PathVariable("id") Long id) {
        log.debug("REST request to get PresenceReunion : {}", id);
        PresenceReunion e = entityService.getOne(id);

        return new ResponseEntity<>(e, HttpStatus.OK);
    }

  /**
     * {@code DELETE  /presenceReunion/:id} : delete the "id" presenceReunion.
     *
     * @param id the id of the presenceReunion to delete.
     * @return the {@link ResponseEntity} with status {@code 204 (NO_CONTENT)}.
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deletePresenceReunion(@PathVariable("id") Long id) {
        log.debug("REST request to delete PresenceReunion : {}", id);
        entityService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

}
