/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-10-05 ( Date ISO 2024-10-05 - Time 15:16:59 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package sn.afrik.tech.solidarite_360.controllers.evt;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import jakarta.validation.Valid;
import sn.afrik.tech.solidarite_360.entities.evt.PresenceEvenement;
import sn.afrik.tech.solidarite_360.services.impl.PresenceEvenementService;


/**
 * REST controller for managing {@link PresenceEvenement}.
 *
 * @author @aek
 */
@RestController
@RequestMapping("/api/presenceEvenement")
public class PresenceEvenementCtrl {

    private final Logger log = LoggerFactory.getLogger(PresenceEvenementCtrl.class);
	
    private final PresenceEvenementService entityService;

 	public PresenceEvenementCtrl (PresenceEvenementService entityService) {
		this.entityService = entityService;
	}

    /**
     * {@code POST  /presenceEvenement} : Create a new presenceEvenement.
     *
     * @param presenceEvenement the presenceEvenement to create.
     * @return the {@link ResponseEntity} with status {@code 201 (Created)} and with body the new presenceEvenement.
     */
	@PostMapping()
	public ResponseEntity<PresenceEvenement> createPresenceEvenement(@RequestBody @Valid PresenceEvenement presenceEvenement) {
         log.debug("REST request to save PresenceEvenement : {}", presenceEvenement);
         return new ResponseEntity<>(entityService.create(presenceEvenement), HttpStatus.CREATED);
    }

   /**
     * {@code PUT  /presenceEvenement} : Updates an existing presenceEvenement.
     *
     * @param presenceEvenement the presenceEvenement to update.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the updated presenceEvenement,
     * or with status {@code 400 (Bad Request)} if the presenceEvenement is not valid,
     * or with status {@code 500 (Internal Server Error)} if the presenceEvenement couldn't be updated.
     */
    @PutMapping()
    public ResponseEntity<PresenceEvenement> updatePresenceEvenement(@Valid @RequestBody PresenceEvenement presenceEvenement) {
        log.debug("REST request to update PresenceEvenement : {}", presenceEvenement);
        PresenceEvenement result = entityService.update(presenceEvenement);
        return ResponseEntity.ok().body(result);
    }

    /**
     * {@code GET  /presenceEvenement} : get all the presenceEvenements.
     *
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the list of presenceEvenement in body.
     */

    @GetMapping()
    public ResponseEntity<List<PresenceEvenement>> getAllPresenceEvenement() {
	    log.debug("REST request to get all presenceEvenements");
        List<PresenceEvenement> lst = entityService.getAll();

        return new ResponseEntity<>(lst,HttpStatus.OK);
    }

    /**
     * {@code GET  /presenceEvenement/:id} : get the "id" presenceEvenement.
     *
     * @param id the id of the presenceEvenement to retrieve.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the presenceEvenement, or with status {@code 404 (Not Found)}.
     */
    @GetMapping(value = "/{id}")
    public ResponseEntity<PresenceEvenement> getOnePresenceEvenement(@PathVariable("id") Long id) {
        log.debug("REST request to get PresenceEvenement : {}", id);
        PresenceEvenement e = entityService.getOne(id);

        return new ResponseEntity<>(e, HttpStatus.OK);
    }

  /**
     * {@code DELETE  /presenceEvenement/:id} : delete the "id" presenceEvenement.
     *
     * @param id the id of the presenceEvenement to delete.
     * @return the {@link ResponseEntity} with status {@code 204 (NO_CONTENT)}.
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deletePresenceEvenement(@PathVariable("id") Long id) {
        log.debug("REST request to delete PresenceEvenement : {}", id);
        entityService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

}
