/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-10-05 ( Date ISO 2024-10-05 - Time 15:16:59 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package sn.afrik.tech.solidarite_360.controllers.evt;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import jakarta.validation.Valid;
import sn.afrik.tech.solidarite_360.entities.evt.Reunion;
import sn.afrik.tech.solidarite_360.services.impl.ReunionService;


/**
 * REST controller for managing {@link Reunion}.
 *
 * @author @aek
 */
@RestController
@RequestMapping("/api/reunion")
public class ReunionCtrl {

    private final Logger log = LoggerFactory.getLogger(ReunionCtrl.class);
	
    private final ReunionService entityService;

 	public ReunionCtrl (ReunionService entityService) {
		this.entityService = entityService;
	}

    /**
     * {@code POST  /reunion} : Create a new reunion.
     *
     * @param reunion the reunion to create.
     * @return the {@link ResponseEntity} with status {@code 201 (Created)} and with body the new reunion.
     */
	@PostMapping()
	public ResponseEntity<Reunion> createReunion(@RequestBody @Valid Reunion reunion) {
         log.debug("REST request to save Reunion : {}", reunion);
         return new ResponseEntity<>(entityService.create(reunion), HttpStatus.CREATED);
    }

   /**
     * {@code PUT  /reunion} : Updates an existing reunion.
     *
     * @param reunion the reunion to update.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the updated reunion,
     * or with status {@code 400 (Bad Request)} if the reunion is not valid,
     * or with status {@code 500 (Internal Server Error)} if the reunion couldn't be updated.
     */
    @PutMapping()
    public ResponseEntity<Reunion> updateReunion(@Valid @RequestBody Reunion reunion) {
        log.debug("REST request to update Reunion : {}", reunion);
        Reunion result = entityService.update(reunion);
        return ResponseEntity.ok().body(result);
    }

    /**
     * {@code GET  /reunion} : get all the reunions.
     *
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the list of reunion in body.
     */

    @GetMapping()
    public ResponseEntity<List<Reunion>> getAllReunion() {
	    log.debug("REST request to get all reunions");
        List<Reunion> lst = entityService.getAll();

        return new ResponseEntity<>(lst,HttpStatus.OK);
    }

    /**
     * {@code GET  /reunion/:id} : get the "id" reunion.
     *
     * @param id the id of the reunion to retrieve.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the reunion, or with status {@code 404 (Not Found)}.
     */
    @GetMapping(value = "/{id}")
    public ResponseEntity<Reunion> getOneReunion(@PathVariable("id") Long id) {
        log.debug("REST request to get Reunion : {}", id);
        Reunion e = entityService.getOne(id);

        return new ResponseEntity<>(e, HttpStatus.OK);
    }

  /**
     * {@code DELETE  /reunion/:id} : delete the "id" reunion.
     *
     * @param id the id of the reunion to delete.
     * @return the {@link ResponseEntity} with status {@code 204 (NO_CONTENT)}.
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteReunion(@PathVariable("id") Long id) {
        log.debug("REST request to delete Reunion : {}", id);
        entityService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

}
