/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-10-05 ( Date ISO 2024-10-05 - Time 15:16:59 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package sn.afrik.tech.solidarite_360.controllers.ref;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import jakarta.validation.Valid;
import sn.afrik.tech.solidarite_360.entities.ref.Fonction;
import sn.afrik.tech.solidarite_360.services.impl.FonctionService;


/**
 * REST controller for managing {@link Fonction}.
 *
 * @author @aek
 */
@RestController
@RequestMapping("/api/fonction")
public class FonctionCtrl {

    private final Logger log = LoggerFactory.getLogger(FonctionCtrl.class);
	
    private final FonctionService entityService;

 	public FonctionCtrl (FonctionService entityService) {
		this.entityService = entityService;
	}

    /**
     * {@code POST  /fonction} : Create a new fonction.
     *
     * @param fonction the fonction to create.
     * @return the {@link ResponseEntity} with status {@code 201 (Created)} and with body the new fonction.
     */
	@PostMapping()
	public ResponseEntity<Fonction> createFonction(@RequestBody @Valid Fonction fonction) {
         log.debug("REST request to save Fonction : {}", fonction);
         return new ResponseEntity<>(entityService.create(fonction), HttpStatus.CREATED);
    }

   /**
     * {@code PUT  /fonction} : Updates an existing fonction.
     *
     * @param fonction the fonction to update.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the updated fonction,
     * or with status {@code 400 (Bad Request)} if the fonction is not valid,
     * or with status {@code 500 (Internal Server Error)} if the fonction couldn't be updated.
     */
    @PutMapping()
    public ResponseEntity<Fonction> updateFonction(@Valid @RequestBody Fonction fonction) {
        log.debug("REST request to update Fonction : {}", fonction);
        Fonction result = entityService.update(fonction);
        return ResponseEntity.ok().body(result);
    }

    /**
     * {@code GET  /fonction} : get all the fonctions.
     *
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the list of fonction in body.
     */

    @GetMapping()
    public ResponseEntity<List<Fonction>> getAllFonction() {
	    log.debug("REST request to get all fonctions");
        List<Fonction> lst = entityService.getAll();

        return new ResponseEntity<>(lst,HttpStatus.OK);
    }

    /**
     * {@code GET  /fonction/:id} : get the "id" fonction.
     *
     * @param id the id of the fonction to retrieve.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the fonction, or with status {@code 404 (Not Found)}.
     */
    @GetMapping(value = "/{id}")
    public ResponseEntity<Fonction> getOneFonction(@PathVariable("id") Long id) {
        log.debug("REST request to get Fonction : {}", id);
        Fonction e = entityService.getOne(id);

        return new ResponseEntity<>(e, HttpStatus.OK);
    }

  /**
     * {@code DELETE  /fonction/:id} : delete the "id" fonction.
     *
     * @param id the id of the fonction to delete.
     * @return the {@link ResponseEntity} with status {@code 204 (NO_CONTENT)}.
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteFonction(@PathVariable("id") Long id) {
        log.debug("REST request to delete Fonction : {}", id);
        entityService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

}
