/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-10-05 ( Date ISO 2024-10-05 - Time 15:16:59 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package sn.afrik.tech.solidarite_360.controllers.doc;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import jakarta.validation.Valid;
import sn.afrik.tech.solidarite_360.entities.doc.Media;
import sn.afrik.tech.solidarite_360.services.impl.MediaService;


/**
 * REST controller for managing {@link Media}.
 *
 * @author @aek
 */
@RestController
@RequestMapping("/api/media")
public class MediaCtrl {

    private final Logger log = LoggerFactory.getLogger(MediaCtrl.class);
	
    private final MediaService entityService;

 	public MediaCtrl (MediaService entityService) {
		this.entityService = entityService;
	}

    /**
     * {@code POST  /media} : Create a new media.
     *
     * @param media the media to create.
     * @return the {@link ResponseEntity} with status {@code 201 (Created)} and with body the new media.
     */
	@PostMapping()
	public ResponseEntity<Media> createMedia(@RequestBody @Valid Media media) {
         log.debug("REST request to save Media : {}", media);
         return new ResponseEntity<>(entityService.create(media), HttpStatus.CREATED);
    }

   /**
     * {@code PUT  /media} : Updates an existing media.
     *
     * @param media the media to update.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the updated media,
     * or with status {@code 400 (Bad Request)} if the media is not valid,
     * or with status {@code 500 (Internal Server Error)} if the media couldn't be updated.
     */
    @PutMapping()
    public ResponseEntity<Media> updateMedia(@Valid @RequestBody Media media) {
        log.debug("REST request to update Media : {}", media);
        Media result = entityService.update(media);
        return ResponseEntity.ok().body(result);
    }

    /**
     * {@code GET  /media} : get all the medias.
     *
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the list of media in body.
     */

    @GetMapping()
    public ResponseEntity<List<Media>> getAllMedia() {
	    log.debug("REST request to get all medias");
        List<Media> lst = entityService.getAll();

        return new ResponseEntity<>(lst,HttpStatus.OK);
    }

    /**
     * {@code GET  /media/:id} : get the "id" media.
     *
     * @param id the id of the media to retrieve.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the media, or with status {@code 404 (Not Found)}.
     */
    @GetMapping(value = "/{id}")
    public ResponseEntity<Media> getOneMedia(@PathVariable("id") Long id) {
        log.debug("REST request to get Media : {}", id);
        Media e = entityService.getOne(id);

        return new ResponseEntity<>(e, HttpStatus.OK);
    }

  /**
     * {@code DELETE  /media/:id} : delete the "id" media.
     *
     * @param id the id of the media to delete.
     * @return the {@link ResponseEntity} with status {@code 204 (NO_CONTENT)}.
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteMedia(@PathVariable("id") Long id) {
        log.debug("REST request to delete Media : {}", id);
        entityService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

}
