/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-10-05 ( Date ISO 2024-10-05 - Time 14:43:01 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package sn.afrik.tech.solidarite_360.services.admin;
import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;

import sn.afrik.tech.solidarite_360.entities.admin.Membre;

/**
 * Service Interface for managing {@link Membre}.
*  @author aek
 */
public interface IMembreService  {
   
    /**
     * create new item for domain
     *
     * @param entity entity to save.
     * @return persisted entity Membre
     */
    Membre create(Membre d);

    /**
     * Update entity. Check before if existing data. If data is empty throw Exception
     *
     * @param entity domain
     * @param id of entity
     * @return Membre
     */
    Membre update(Membre d);

    /**
     * get Membre by id. Can be return empty
     *
     * @param id the id of the entity.
     * @return Membre
     */
    Membre getOne(String id) ;

    /**
     * Get all entities
     *
     * @return list of entities List<Membre>
     */
    List<Membre> getAll();

    /**
     * Count item in entity
     *
     * @return long 
     */
    long getTotal();

    /**
     * Delete record by id
     *  
     */
    void delete(String id);

    /**
     * Find all with pagination
     *
     * @return Page<Membre>  
     */
    Page<Membre> findAllPaginate(Pageable pageable);

    /**
     * Find all with pagination  by criteria 
     *
     * @return Page<Membre>  
     */
	Page<Membre> findAllSpecification(Specification<Membre> specs, Pageable pageable);

}
