/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-10-05 ( Date ISO 2024-10-05 - Time 15:16:58 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package sn.afrik.tech.solidarite_360.controllers.tresorerie;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import jakarta.validation.Valid;
import sn.afrik.tech.solidarite_360.entities.tresorerie.Cotisation;
import sn.afrik.tech.solidarite_360.services.impl.CotisationService;


/**
 * REST controller for managing {@link Cotisation}.
 *
 * @author @aek
 */
@RestController
@RequestMapping("/api/cotisation")
public class CotisationCtrl {

    private final Logger log = LoggerFactory.getLogger(CotisationCtrl.class);
	
    private final CotisationService entityService;

 	public CotisationCtrl (CotisationService entityService) {
		this.entityService = entityService;
	}

    /**
     * {@code POST  /cotisation} : Create a new cotisation.
     *
     * @param cotisation the cotisation to create.
     * @return the {@link ResponseEntity} with status {@code 201 (Created)} and with body the new cotisation.
     */
	@PostMapping()
	public ResponseEntity<Cotisation> createCotisation(@RequestBody @Valid Cotisation cotisation) {
         log.debug("REST request to save Cotisation : {}", cotisation);
         return new ResponseEntity<>(entityService.create(cotisation), HttpStatus.CREATED);
    }

   /**
     * {@code PUT  /cotisation} : Updates an existing cotisation.
     *
     * @param cotisation the cotisation to update.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the updated cotisation,
     * or with status {@code 400 (Bad Request)} if the cotisation is not valid,
     * or with status {@code 500 (Internal Server Error)} if the cotisation couldn't be updated.
     */
    @PutMapping()
    public ResponseEntity<Cotisation> updateCotisation(@Valid @RequestBody Cotisation cotisation) {
        log.debug("REST request to update Cotisation : {}", cotisation);
        Cotisation result = entityService.update(cotisation);
        return ResponseEntity.ok().body(result);
    }

    /**
     * {@code GET  /cotisation} : get all the cotisations.
     *
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the list of cotisation in body.
     */

    @GetMapping()
    public ResponseEntity<List<Cotisation>> getAllCotisation() {
	    log.debug("REST request to get all cotisations");
        List<Cotisation> lst = entityService.getAll();

        return new ResponseEntity<>(lst,HttpStatus.OK);
    }

    /**
     * {@code GET  /cotisation/:id} : get the "id" cotisation.
     *
     * @param id the id of the cotisation to retrieve.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the cotisation, or with status {@code 404 (Not Found)}.
     */
    @GetMapping(value = "/{id}")
    public ResponseEntity<Cotisation> getOneCotisation(@PathVariable("id") Long id) {
        log.debug("REST request to get Cotisation : {}", id);
        Cotisation e = entityService.getOne(id);

        return new ResponseEntity<>(e, HttpStatus.OK);
    }

  /**
     * {@code DELETE  /cotisation/:id} : delete the "id" cotisation.
     *
     * @param id the id of the cotisation to delete.
     * @return the {@link ResponseEntity} with status {@code 204 (NO_CONTENT)}.
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteCotisation(@PathVariable("id") Long id) {
        log.debug("REST request to delete Cotisation : {}", id);
        entityService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

}
