/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-10-05 ( Date ISO 2024-10-05 - Time 15:16:58 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package sn.afrik.tech.solidarite_360.controllers.tresorerie;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import jakarta.validation.Valid;
import sn.afrik.tech.solidarite_360.entities.tresorerie.Depense;
import sn.afrik.tech.solidarite_360.services.impl.DepenseService;


/**
 * REST controller for managing {@link Depense}.
 *
 * @author @aek
 */
@RestController
@RequestMapping("/api/depense")
public class DepenseCtrl {

    private final Logger log = LoggerFactory.getLogger(DepenseCtrl.class);
	
    private final DepenseService entityService;

 	public DepenseCtrl (DepenseService entityService) {
		this.entityService = entityService;
	}

    /**
     * {@code POST  /depense} : Create a new depense.
     *
     * @param depense the depense to create.
     * @return the {@link ResponseEntity} with status {@code 201 (Created)} and with body the new depense.
     */
	@PostMapping()
	public ResponseEntity<Depense> createDepense(@RequestBody @Valid Depense depense) {
         log.debug("REST request to save Depense : {}", depense);
         return new ResponseEntity<>(entityService.create(depense), HttpStatus.CREATED);
    }

   /**
     * {@code PUT  /depense} : Updates an existing depense.
     *
     * @param depense the depense to update.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the updated depense,
     * or with status {@code 400 (Bad Request)} if the depense is not valid,
     * or with status {@code 500 (Internal Server Error)} if the depense couldn't be updated.
     */
    @PutMapping()
    public ResponseEntity<Depense> updateDepense(@Valid @RequestBody Depense depense) {
        log.debug("REST request to update Depense : {}", depense);
        Depense result = entityService.update(depense);
        return ResponseEntity.ok().body(result);
    }

    /**
     * {@code GET  /depense} : get all the depenses.
     *
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the list of depense in body.
     */

    @GetMapping()
    public ResponseEntity<List<Depense>> getAllDepense() {
	    log.debug("REST request to get all depenses");
        List<Depense> lst = entityService.getAll();

        return new ResponseEntity<>(lst,HttpStatus.OK);
    }

    /**
     * {@code GET  /depense/:id} : get the "id" depense.
     *
     * @param id the id of the depense to retrieve.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the depense, or with status {@code 404 (Not Found)}.
     */
    @GetMapping(value = "/{id}")
    public ResponseEntity<Depense> getOneDepense(@PathVariable("id") Long id) {
        log.debug("REST request to get Depense : {}", id);
        Depense e = entityService.getOne(id);

        return new ResponseEntity<>(e, HttpStatus.OK);
    }

  /**
     * {@code DELETE  /depense/:id} : delete the "id" depense.
     *
     * @param id the id of the depense to delete.
     * @return the {@link ResponseEntity} with status {@code 204 (NO_CONTENT)}.
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteDepense(@PathVariable("id") Long id) {
        log.debug("REST request to delete Depense : {}", id);
        entityService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

}
