/*
 * Java domain class for entity "Validation" 
 * Created on 2024-10-05 ( Date ISO 2024-10-05 - Time 14:03:30 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package sn.afrik.tech.solidarite_360.repositories;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import sn.afrik.tech.solidarite_360.entities.Validation;

/**
 * <h2>ValidationRepository</h2>
 *
 * createdAt : 05-10-2024 - Time 14:03:30
 * 
 * @author aek
 */
@Repository
public interface ValidationRepository  extends JpaRepository<Validation, Long> , JpaSpecificationExecutor<Validation> {

}
