/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-10-05 ( Date ISO 2024-10-05 - Time 15:16:59 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package sn.afrik.tech.solidarite_360.controllers.admin;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import jakarta.validation.Valid;
import sn.afrik.tech.solidarite_360.entities.IndicateurPerformance;
import sn.afrik.tech.solidarite_360.services.impl.IndicateurPerformanceService;


/**
 * REST controller for managing {@link IndicateurPerformance}.
 *
 * @author @aek
 */
@RestController
@RequestMapping("/api/indicateurPerformance")
public class IndicateurPerformanceCtrl {

    private final Logger log = LoggerFactory.getLogger(IndicateurPerformanceCtrl.class);
	
    private final IndicateurPerformanceService entityService;

 	public IndicateurPerformanceCtrl (IndicateurPerformanceService entityService) {
		this.entityService = entityService;
	}

    /**
     * {@code POST  /indicateurPerformance} : Create a new indicateurPerformance.
     *
     * @param indicateurPerformance the indicateurPerformance to create.
     * @return the {@link ResponseEntity} with status {@code 201 (Created)} and with body the new indicateurPerformance.
     */
	@PostMapping()
	public ResponseEntity<IndicateurPerformance> createIndicateurPerformance(@RequestBody @Valid IndicateurPerformance indicateurPerformance) {
         log.debug("REST request to save IndicateurPerformance : {}", indicateurPerformance);
         return new ResponseEntity<>(entityService.create(indicateurPerformance), HttpStatus.CREATED);
    }

   /**
     * {@code PUT  /indicateurPerformance} : Updates an existing indicateurPerformance.
     *
     * @param indicateurPerformance the indicateurPerformance to update.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the updated indicateurPerformance,
     * or with status {@code 400 (Bad Request)} if the indicateurPerformance is not valid,
     * or with status {@code 500 (Internal Server Error)} if the indicateurPerformance couldn't be updated.
     */
    @PutMapping()
    public ResponseEntity<IndicateurPerformance> updateIndicateurPerformance(@Valid @RequestBody IndicateurPerformance indicateurPerformance) {
        log.debug("REST request to update IndicateurPerformance : {}", indicateurPerformance);
        IndicateurPerformance result = entityService.update(indicateurPerformance);
        return ResponseEntity.ok().body(result);
    }

    /**
     * {@code GET  /indicateurPerformance} : get all the indicateurPerformances.
     *
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the list of indicateurPerformance in body.
     */

    @GetMapping()
    public ResponseEntity<List<IndicateurPerformance>> getAllIndicateurPerformance() {
	    log.debug("REST request to get all indicateurPerformances");
        List<IndicateurPerformance> lst = entityService.getAll();

        return new ResponseEntity<>(lst,HttpStatus.OK);
    }

    /**
     * {@code GET  /indicateurPerformance/:id} : get the "id" indicateurPerformance.
     *
     * @param id the id of the indicateurPerformance to retrieve.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the indicateurPerformance, or with status {@code 404 (Not Found)}.
     */
    @GetMapping(value = "/{id}")
    public ResponseEntity<IndicateurPerformance> getOneIndicateurPerformance(@PathVariable("id") Long id) {
        log.debug("REST request to get IndicateurPerformance : {}", id);
        IndicateurPerformance e = entityService.getOne(id);

        return new ResponseEntity<>(e, HttpStatus.OK);
    }

  /**
     * {@code DELETE  /indicateurPerformance/:id} : delete the "id" indicateurPerformance.
     *
     * @param id the id of the indicateurPerformance to delete.
     * @return the {@link ResponseEntity} with status {@code 204 (NO_CONTENT)}.
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteIndicateurPerformance(@PathVariable("id") Long id) {
        log.debug("REST request to delete IndicateurPerformance : {}", id);
        entityService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

}
