/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-10-05 ( Date ISO 2024-10-05 - Time 15:16:59 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package sn.afrik.tech.solidarite_360.controllers.admin;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import jakarta.validation.Valid;
import sn.afrik.tech.solidarite_360.entities.admin.Membre;
import sn.afrik.tech.solidarite_360.services.impl.MembreService;


/**
 * REST controller for managing {@link Membre}.
 *
 * @author @aek
 */
@RestController
@RequestMapping("/api/membre")
public class MembreCtrl {

    private final Logger log = LoggerFactory.getLogger(MembreCtrl.class);
	
    private final MembreService entityService;

 	public MembreCtrl (MembreService entityService) {
		this.entityService = entityService;
	}

    /**
     * {@code POST  /membre} : Create a new membre.
     *
     * @param membre the membre to create.
     * @return the {@link ResponseEntity} with status {@code 201 (Created)} and with body the new membre.
     */
	@PostMapping()
	public ResponseEntity<Membre> createMembre(@RequestBody @Valid Membre membre) {
         log.debug("REST request to save Membre : {}", membre);
         return new ResponseEntity<>(entityService.create(membre), HttpStatus.CREATED);
    }

   /**
     * {@code PUT  /membre} : Updates an existing membre.
     *
     * @param membre the membre to update.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the updated membre,
     * or with status {@code 400 (Bad Request)} if the membre is not valid,
     * or with status {@code 500 (Internal Server Error)} if the membre couldn't be updated.
     */
    @PutMapping()
    public ResponseEntity<Membre> updateMembre(@Valid @RequestBody Membre membre) {
        log.debug("REST request to update Membre : {}", membre);
        Membre result = entityService.update(membre);
        return ResponseEntity.ok().body(result);
    }

    /**
     * {@code GET  /membre} : get all the membres.
     *
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the list of membre in body.
     */

    @GetMapping()
    public ResponseEntity<List<Membre>> getAllMembre() {
	    log.debug("REST request to get all membres");
        List<Membre> lst = entityService.getAll();

        return new ResponseEntity<>(lst,HttpStatus.OK);
    }

    /**
     * {@code GET  /membre/:id} : get the "id" membre.
     *
     * @param id the id of the membre to retrieve.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the membre, or with status {@code 404 (Not Found)}.
     */
    @GetMapping(value = "/{id}")
    public ResponseEntity<Membre> getOneMembre(@PathVariable("id") String id) {
        log.debug("REST request to get Membre : {}", id);
        Membre e = entityService.getOne(id);

        return new ResponseEntity<>(e, HttpStatus.OK);
    }

  /**
     * {@code DELETE  /membre/:id} : delete the "id" membre.
     *
     * @param id the id of the membre to delete.
     * @return the {@link ResponseEntity} with status {@code 204 (NO_CONTENT)}.
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteMembre(@PathVariable("id") String id) {
        log.debug("REST request to delete Membre : {}", id);
        entityService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

}
