/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-10-05 ( Date ISO 2024-10-05 - Time 14:43:01 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package sn.afrik.tech.solidarite_360.services.evt;
import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;

import sn.afrik.tech.solidarite_360.entities.evt.PresenceActivite;

/**
 * Service Interface for managing {@link PresenceActivite}.
*  @author aek
 */
public interface IPresenceActiviteService  {
   
    /**
     * create new item for domain
     *
     * @param entity entity to save.
     * @return persisted entity PresenceActivite
     */
    PresenceActivite create(PresenceActivite d);

    /**
     * Update entity. Check before if existing data. If data is empty throw Exception
     *
     * @param entity domain
     * @param id of entity
     * @return PresenceActivite
     */
    PresenceActivite update(PresenceActivite d);

    /**
     * get PresenceActivite by id. Can be return empty
     *
     * @param id the id of the entity.
     * @return PresenceActivite
     */
    PresenceActivite getOne(Long id) ;

    /**
     * Get all entities
     *
     * @return list of entities List<PresenceActivite>
     */
    List<PresenceActivite> getAll();

    /**
     * Count item in entity
     *
     * @return long 
     */
    long getTotal();

    /**
     * Delete record by id
     *  
     */
    void delete(Long id);

    /**
     * Find all with pagination
     *
     * @return Page<PresenceActivite>  
     */
    Page<PresenceActivite> findAllPaginate(Pageable pageable);

    /**
     * Find all with pagination  by criteria 
     *
     * @return Page<PresenceActivite>  
     */
	Page<PresenceActivite> findAllSpecification(Specification<PresenceActivite> specs, Pageable pageable);

}
