/*
 * Java domain class for entity "Media" 
 * Created on 2024-10-05 ( Date ISO 2024-10-05 - Time 12:31:54 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package sn.afrik.tech.solidarite_360.repositories.doc;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import sn.afrik.tech.solidarite_360.entities.doc.Media;

/**
 * <h2>MediaRepository</h2>
 *
 * createdAt : 05-10-2024 - Time 12:31:54
 * 
 * @author aek
 */
@Repository
public interface MediaRepository  extends JpaRepository<Media, Long> , JpaSpecificationExecutor<Media> {

}
