/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-10-05 ( Date ISO 2024-10-05 - Time 14:43:03 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package sn.afrik.tech.solidarite_360.services;
import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;

import sn.afrik.tech.solidarite_360.entities.Tache;

/**
 * Service Interface for managing {@link Tache}.
*  @author aek
 */
public interface ITacheService  {
   
    /**
     * create new item for domain
     *
     * @param entity entity to save.
     * @return persisted entity Tache
     */
    Tache create(Tache d);

    /**
     * Update entity. Check before if existing data. If data is empty throw Exception
     *
     * @param entity domain
     * @param id of entity
     * @return Tache
     */
    Tache update(Tache d);

    /**
     * get Tache by id. Can be return empty
     *
     * @param id the id of the entity.
     * @return Tache
     */
    Tache getOne(Long id) ;

    /**
     * Get all entities
     *
     * @return list of entities List<Tache>
     */
    List<Tache> getAll();

    /**
     * Count item in entity
     *
     * @return long 
     */
    long getTotal();

    /**
     * Delete record by id
     *  
     */
    void delete(Long id);

    /**
     * Find all with pagination
     *
     * @return Page<Tache>  
     */
    Page<Tache> findAllPaginate(Pageable pageable);

    /**
     * Find all with pagination  by criteria 
     *
     * @return Page<Tache>  
     */
	Page<Tache> findAllSpecification(Specification<Tache> specs, Pageable pageable);

}
