/*
 * Java domain class for entity "Depense" 
 * Created on 2024-10-05 ( Date ISO 2024-10-05 - Time 14:39:22 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package sn.afrik.tech.solidarite_360.repositories.tresorerie;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import sn.afrik.tech.solidarite_360.entities.tresorerie.Depense;

/**
 * <h2>DepenseRepository</h2>
 *
 * createdAt : 05-10-2024 - Time 14:39:22
 * 
 * @author aek
 */
@Repository
public interface DepenseRepository  extends JpaRepository<Depense, Long> , JpaSpecificationExecutor<Depense> {

}
