/*
 * Java domain class for entity "Evenement" 
 * Created on 2024-10-05 ( Date ISO 2024-10-05 - Time 12:31:53 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package sn.afrik.tech.solidarite_360.repositories.evt;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import sn.afrik.tech.solidarite_360.entities.evt.Evenement;

/**
 * <h2>EvenementRepository</h2>
 *
 * createdAt : 05-10-2024 - Time 12:31:53
 * 
 * @author aek
 */
@Repository
public interface EvenementRepository  extends JpaRepository<Evenement, Long> , JpaSpecificationExecutor<Evenement> {

}
