/*
 * Java domain class for entity "Reunion" 
 * Created on 2024-10-05 ( Date ISO 2024-10-05 - Time 12:31:54 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package sn.afrik.tech.solidarite_360.repositories.evt;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import sn.afrik.tech.solidarite_360.entities.evt.Reunion;

/**
 * <h2>ReunionRepository</h2>
 *
 * createdAt : 05-10-2024 - Time 12:31:54
 * 
 * @author aek
 */
@Repository
public interface ReunionRepository  extends JpaRepository<Reunion, Long> , JpaSpecificationExecutor<Reunion> {

}
