/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-10-05 ( Date ISO 2024-10-05 - Time 14:43:01 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package sn.afrik.tech.solidarite_360.services.tresorerie;
import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;

import sn.afrik.tech.solidarite_360.entities.tresorerie.Recette;

/**
 * Service Interface for managing {@link Recette}.
*  @author aek
 */
public interface IRecetteService  {
   
    /**
     * create new item for domain
     *
     * @param entity entity to save.
     * @return persisted entity Recette
     */
    Recette create(Recette d);

    /**
     * Update entity. Check before if existing data. If data is empty throw Exception
     *
     * @param entity domain
     * @param id of entity
     * @return Recette
     */
    Recette update(Recette d);

    /**
     * get Recette by id. Can be return empty
     *
     * @param id the id of the entity.
     * @return Recette
     */
    Recette getOne(Long id) ;

    /**
     * Get all entities
     *
     * @return list of entities List<Recette>
     */
    List<Recette> getAll();

    /**
     * Count item in entity
     *
     * @return long 
     */
    long getTotal();

    /**
     * Delete record by id
     *  
     */
    void delete(Long id);

    /**
     * Find all with pagination
     *
     * @return Page<Recette>  
     */
    Page<Recette> findAllPaginate(Pageable pageable);

    /**
     * Find all with pagination  by criteria 
     *
     * @return Page<Recette>  
     */
	Page<Recette> findAllSpecification(Specification<Recette> specs, Pageable pageable);

}
